### PR TITLE
Fixed foreign and primary keys problem

### PR DESCRIPTION
**Pull request by GastonFenske**

### CODE REVIEW

**Review by DelfinaQuinteros — APPROVED** [review]
finally, thank you for so much

**Review by DaniBeato — APPROVED** [review]
Nice work! Finally, primary key´s and foreign key´s problems have been solved. Thanks you a lot!

**Comment by fpiruzi** [comment]
Did you update the version? what was the issue? @DaniBeato @DelfinaQuinteros @GastonFenske

**Review by JulianNavarrete — APPROVED** [review]
Works fine

**Pull request merged**
